### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by usask-rc** [globus/globus-publish-dspace#29]
Hi Jim, I don't see a LICENSE file or any other indication as to what license this source code is released under.  Also in checking Dspace source, I think you need to pull in a copy of this:

https://github.com/DSpace/DSpace/blob/master/LICENSE

**Comment by jimPruyne** [comment]
This is probably a good idea. I may have to review how it should be worded given the hybrid nature of the code that's here now.
