### ISSUE TITLE
Remove references to GoAuth

### ISSUE THREAD

**Issue by jimPruyne** [globus/globus-publish-dspace#4]

**Comment by mattias-lidman** [comment]
:+1:

**Comment by jimPruyne** [comment]
@mattias-lidman kinda creeped me out, I didn't think anyone else was aware of what's going on in this repo.

**Comment by bjmc** [comment]
:eyes:

**Comment by mattias-lidman** [comment]
I think everyone got auto-subscribed to everything a while back.
